title: "Etienne Tajeuna"
description: "Research in graph representation learning, time series analysis and survival analysis."
url: "https://etiennetajeuna.github.io"
baseurl: ""

author:
  name: "Etienne Tajeuna"
  email: "your.email@uqo.ca"

minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/yourgithubusername"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/your-linkedin/"
    - title: Google Scholar
      icon: google-scholar
      url: "https://scholar.google.com/"

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
